grafana/provisioning/dashboards/perf.json

In this PR, we attempt to make the current CPU usage graph for `lnd`
more accurate. AFAICT, the `*10` that we had was completely superfluous,
and omitting that seems to produce a more accurate CPU usage reading. In
the future, we may want to use something like [`Node
Exporter`](https://prometheus.io/docs/guides/node-exporter/) as we can
obtain richer information such as the idle CPU time, or the amount of
disk space left on the instance.

dashboards: more accurate CPU usage for the perf dashboard

---

grafana/provisioning/dashboards/perf.json

In this commit, we fix an oversight that would cause us to display heap
information for both `lnd` _and_ `lndmon`. The prior commit that added
this information failed to filter it out for only `lnd`, resulting in a
noisier graph than expected.

dashboards: only display heap info for lnd

---

INSTALL.md

Small documentation update.
Fixes https://github.com/lightninglabs/lndmon/issues/27

docs: add default grafana password to install instructions

---

grafana/provisioning/dashboards/network.json

This PR:
- overlays dual axis block height w/ network channel count
- makes channel count integral (instead of abbreviated in kilo-channels)
- overlays dual axis block height w/ network capacity
- corrects units for network capacity to btc instead of sats

grafana/network: overlay capacity and channels with block height

---

grafana/provisioning/dashboards/peers.json

In this commit, we switch to using an `irate` over the past minute for
the peer graphs. The cumulative graph wasn't very helpful, since it can
be skewed when peers connect/reconnect. This new `irate` format is
better as you can at a glance, spot anomalies (spikes in sent/recv)
easily.
We also fix some graphs that were graph satoshis instead of bytes (kek),
and use a longer interval for the peer flappiness graph to make it
smoother.
Nu graphs:

dashboards: switch to irate for peer bytes sent/recv

---

collectors/graph_collector.go

`docker-compose build` is failing with:
```
../../collectors/graph_collector.go:297:15: resp.NumZombies undefined (type *lnrpc.ChannelGraph has no field or method NumZombies)
ERROR: Service 'lndmon' failed to build: The command '/bin/sh -c cd /go/src/github.com/lightninglabs/lndmon/cmd/lndmon && go build' returned a non-zero code: 2
```
Probably related to #49, although I didn't check all the way back to v0.7.1 for the proto change so I will get somebody else to reproduce.

Fix Build: Get zombie channel count from network info

---

collectors/channels_collector.go
grafana/provisioning/dashboards/channels.json

This PR adds the remote node's uptime percentage to the node stats dashboard per channel we have open. This change relies on the experimental uptime field in `lnstchannels``.
This change could be generalized to adding uptime for all peers if we updated peer tracking to `listpeers` in lnd (which may be worth doing), or moved onto the peers dashboard if we call `listchannels` in the peers collector then just set uptime for the peers that we currently have channels for.

Add Channel Uptime Percentage

---

.travis.yml
Makefile

This PR adds a makefile which builds and lints lndmon and a minimal travis config which lints and builds lndmon. 
Edit: I don't have perms to enable travis for the repo. @Roasbeef please will you enable to check that travis runs as expected for this one 🙏

Add makefile and travis config

---

collectors/info_collector.go

This adds an metric for collecting miscellaneous node information
Currently collects
* Alias
* Pubkey
* Version
```
lnd_info{alias="02e47c1ee7c53fdd445f",pubkey="02e47c1007c43fdd9423f6e473a9bda81de6e95784749e10bf2dcaf95267c39f38",version="0.7.0-beta commit=v0.7.0-beta"} 0
```

Add Info Metric 

---

.gitignore
collectors/chain_collector.go
collectors/channel_collector_test.go
collectors/channels_collector.go
collectors/graph_collector.go
collectors/info_collector.go
collectors/peer_collector.go
collectors/prometheus.go
collectors/wallet_collector.go
config.go
go.mod
go.sum
lndmon.go

This PR adds a cumulative metric for the routing fee that senders need to pay to the last hop to reach the node that is being monitored. It is an indication of the quality of inbound liquidity.
Example output to Prometheus:
```
inbound_fee{amount="0.001 BTC"} 4e-05
inbound_fee{amount="0.002 BTC"} 4.5e-05
inbound_fee{amount="0.004 BTC"} 4.75e-05
inbound_fee{amount="0.008 BTC"} 7.75e-05
inbound_fee{amount="0.016 BTC"} 0.00030125
inbound_fee{amount="0.032 BTC"} 0.000650625
inbound_fee{amount="0.064 BTC"} 0.00082515625
inbound_fee{amount="0.128 BTC"} 0.000912578125
```
When used in a primary-gateway setup, it is typically required to ignore the internal channels for this metric. This can be indicated by passing the pubkey of the primary node via the `--primarynode` command line flag.

collectors: add inbound fee metric

---

Dockerfile
collectors/prometheus.go

In this PR, we hook up a proper error logger for `promhttp`, which means that we'll now get error logging if Prometheus encounters an error during scraping. We also modify the default arguments to allow the scraper to continue if if runs into any errors along the way.

collectors: add proper scraping http error logging, continue if error encountered

---

config.go
lndmon.go

Previous changes set lndmon to only use the macaroon path that is set
when we use docker-compose and the mounted macaroons volume. This commit
updates lndmon to use the macaroon dir path and adds a macaroon name (so
that macaroons other than the readonly macaroon could be used). This
allows standalone lndmon containers that do not use our docker-compose
setup to specify where their macaroons are.

config: allow specifying of macaroon directory and name

---

collectors/wallet_collector.go

Graphs using the transaction confirmations metric were removed in 75867a33dd890b8ce90b21ed3a17eb42c9c0881c, and it is causing issues in #47.
This PR removes the metric entirely, since it is unused. Will continue to debug the root cause of the issue on the original issue.

walletcollector: remove unused metric

---

grafana/provisioning/dashboards/routing.json

This PR makes two small changes to the routing dashboard:
1. Show channel ID labels as a table for panels where we may have many channels, this makes it easier to select individual channels and more readable for nodes with many channels
2. Change resolution rate to use `increase` over `irate`, this display the change in our count of settled/failed htlcs

routing: dashboard tweaks

---

collectors/channels_collector.go
grafana/provisioning/dashboards/channels.json

This PR adds metrics so that a prometheus alert can be set up when a force-close happens. This is an event that unfortunately still seems to occur occasionally.
Example of an alert that becomes active if at least one channel was force-closed in the past 24 hours:
`round(sum(delta(lnd_closed_channels_total{type="local_force"}[1d]) or delta(lnd_closed_channels_total{type="remote_force"}[1d]) or delta(lnd_channels_pending_total{state="pending_force_close"}[1d]))) > 0`

collectors: add close metrics

---

collectors/prometheus.go
config.go
lndmon.go

`lndmon` is known (reported by multiple users) to cause high cpu load problems for lnd. This is cause by the `DescribeGraph` call which is really too heavy for frequent scraping.
This PR adds a command line flag to disable the graph metrics.

config: add --disablegraph

---

grafana/provisioning/dashboards/chain.json
grafana/provisioning/dashboards/channels.json
grafana/provisioning/dashboards/network.json
grafana/provisioning/dashboards/peers.json
grafana/provisioning/dashboards/perf.json
grafana/provisioning/dashboards/routing.json

Alternate version of https://github.com/lightninglabs/lndmon/pull/42 that allows filtering by node and namespace.

Kubernetes compatible dashboards (alt)

---

collectors/wallet_collector.go

Since the introduction of
https://github.com/lightningnetwork/lnd/commit/afc53d1c52f457ba24dc2a82d0f78e87865113b5,
lnd will create 255 new wallets. Those might never be used but metrics
are being sent, polluting the metric space.
This PR only send metrics when keycount is > 0 on both internal and
external branches.

Prevent sending key count when 0.

---

config.go
lndmon.go

This PR adds an option to set the [lndclient RPCTimeout](https://github.com/lightninglabs/lndclient/blob/75630fe714237f8b17275325f859f96c30a880ea/lnd_services.go#L151-L154) when initializing lndclient. This gives lndmon users the option to increase the timeout beyond the default 30 seconds in cases where the metrics take longer to return.
Note: If not specified, this argument defaults to 30 seconds, which is the lndclient default.
Additional context:
We use lndmon for our lnd nodes running in Kubernetes and get frequent timeouts due to latency specific to nodes running with a PostgreSQL backend. As such, it often takes longer than 30 seconds for lndmon to gather metrics resulting in our lndmon pods frequently going into a crashloop status. In …

config: add rpctimeout

---

collectors/channels_collector.go
tools/Dockerfile

This commit changes how we collect limbo balances to calculate summaries instead of separate series by channel, peer, status etc. Having just the summaries makes it possible to correctly select the last known total value which was previously not feasible when summarizing over longer periods due to values with channel/peer specific labels getting "stuck".

collectors: summarize limbo channel balances to avoid stuck values

---

collectors/htlcs_collector.go

A previous PR (https://github.com/lightninglabs/lndmon/pull/96) introduced a new bug where we forwarded the final and subscribed events to record them as resolution which isn't needed. This PR fixes that problem.

collectors: remove unneded resoltion when processing final/subscribed htlc events

---

collectors/chain_collector.go
metrics.md

Similar to #40, but this time for synced_to_graph as a metric.
Also added a mention to synced_to_chain in metrics.md

Added synced_to_graph metric

---

collectors/prometheus.go
config.go
lndmon.go

Over 76k entries are registered for `lnd_htlcs_resolved_htlcs` on the Prometheus endpoint in less than a week, leading to huge amounts of data being consumed by the Prometheus server (around 10MB per request). 
```
% cat metrics | sort | uniq -c | sort -nr | head -10
65926 lnd_htlcs_resolved_htlcs
8404 lnd_htlcs_resolution_time_bucket
764 lnd_htlcs_resolution_time_sum
764 lnd_htlcs_resolution_time_count
41 lnd_channels_updates_count
41 lnd_channels_unsettled_balance
41 lnd_channels_sent_sat
41 lnd_channels_received_sat
41 lnd_channels_pending_htlc_count
41 lnd_channels_fee_per_kw
```

Add a toggle to disable the HTLC monitor metrics

---

collectors/channels_collector.go
collectors/prometheus.go
lndmon.go

Currently we call closedChannels once per scrape, this can be fairly expensive for LND's grpcServer. This PR will add:
* a cache map that we populate with a ticker that fires per 10m
* a warmup call during startup that sets the initial value of `closedChannels`
* modifications to return the cache map contents instead of calling the `closedChannels` GRPC endpoint

lndmon: cache closedChannels response

---

post_start/script/set_default_graf_dash.sh

Added the following env vars in the set_default_graf_dash.sh script, while keeping the default values in case they're not set:
- GRAFANA_USER
- GRAFANA_PASS
- GRAFANA_HOST
- GRAFANA_PORT
This is very helpful when deploying with Docker or in a Kubernetes cluster. You can set the env vars in the docker-compose file, or your kubernetes yaml or helm charts.

Add env vars to the grafana connection of post_start script. 

---

collectors/prometheus.go

Prevents htlc stream from being initialised when it isn't needed
Fix for https://github.com/lightninglabs/lndmon/issues/103

collectors: do not init htlc monitor when htlc monitoring is disabled

---

collectors/chain_collector.go
collectors/channels_collector.go
collectors/errors.go
collectors/prometheus.go

Attempt to fix https://github.com/lightninglabs/lndmon/issues/109.
Since the lnd `GetInfo` call sometimes takes way longer than average, we
don't want to shut down on just a timeout.

collectors: don't shut down on timeout on `GetInfo` RPC call

---

config.go

Is there anything more than this needed to enable signet support?
Fixes #80

config: add support for signet

---

.github/workflows/main.yml
collectors/log.go
collectors/payments_collector.go
collectors/prometheus.go
config.go
lndmon.go

Add support for real time tracking of counters for payments and attempts. These can be used to compute and create visualizations for things like average payment throughput and average # of attempts per payment.
```
rate(lnd_total_payments[5m])
rate(lnd_total_htlc_attempts[30m]) / rate(lnd_total_payments[30m])
```
- The information is obtained in real time from **_lnd_** using the **_TrackPayments_** RPC.
After making payments between two directly connected nodes:
```
alice-64db66cb64-g4sh2:/# curl -s http://localhost:8990/metrics | grep lnd_total
lnd_total_htlc_attempts 5
lnd_total_payments 5
```

collectors: collect payment and attempt counts
